### ISSUE TITLE
Information on all "downloadable" USIs 

### ISSUE THREAD

**Issue by roman-bushuiev** [Wang-Bioinformatics-Lab/downloadpublicdata#20]
Hi!

Thank you for this very useful package. It simplifies the automated downloading of MS data so much!

I would like to ask if there is a way to get a list of all USIs that can be downloaded. For example, I am aware of the [table here](https://gnps-datasetcache.ucsd.edu/datasette/database/filename), but there seems to be no way to download the full table. At least, I couldn't find a way to download a CSV with more than the first 50,000 rows. :) The table also lists only paths to GNPS and not, for example, paths to MetaboLights. It would be great to have such a table containing all the "downloadable" USIs. Is it available anywhere?

Thank you in advance!
Roman

**Comment by roman-bushuiev** [comment]
We would like to make the code for building [GeMS datasets](https://chemrxiv.org/engage/chemrxiv/article-details/6626775021291e5d1d61967f) publicly available, and the combination of the `downloadpublicdata` package and such a table would significantly simplify and upgrade our codebase.

**Comment by mwang87** [comment]
Hey @roman-bushuiev thanks for the question. Yes, we've sort of solved this problem in the updated datasetcache on the GNPS2 side. 

The main website is here, much newer version than the UCSD version:

datasetcache.gnps2.org

One thing we've done is do pan-repository, that is highlighted in this paper:

https://chemrxiv.org/engage/chemrxiv/article-details/661cd188418a5379b0df32c2

What you can use is a collapsed new version of all MRI (file version of USI) across all repositories:

https://datasetcache.gnps2.org/datasette/database/uniquemri

We also have a dump to make things easier but I've gotta document this so the download is super fast. 

Also, I think thats a great idea for the GeMS - if you can create a MRI csv file, then point people to this download utility, it'll be super easy for people to reproduce the data used for training. Let me know how it goes!

**Comment by roman-bushuiev** [comment]
Hi @mwang87! Thank you for your reply. It's exactly what I was looking for. I will create a MRI csv file and point people to this package. I also think that it's the best approach.
